# Generated by Django 6.1 on 2026-08-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0021_emergencycontact_employeeaddress_employeeeducation_and_more'),
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='leave_type',
        ),
        migrations.AddConstraint(
            model_name='employeeleavebalance',
            constraint=models.UniqueConstraint(fields=('employee', 'leave_type', 'year'), name='unique_employee_leave_balance_per_year'),
        ),
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
    ]
