# Generated by Django 6.1 on 2026-08-31 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_leaverequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleavebalance',
            name='leave_type',
            field=models.CharField(choices=[('casual', 'Casual'), ('sick', 'Sick'), ('earned', 'Earned'), ('annual', 'Annual'), ('emergency', 'Emergency'), ('maternity', 'Maternity'), ('paternity', 'Paternity'), ('bereavement', 'Bereavement'), ('compensatory', 'Compensatory'), ('unpaid', 'Unpaid')], max_length=30),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('casual', 'Casual'), ('sick', 'Sick'), ('earned', 'Earned'), ('annual', 'Annual'), ('emergency', 'Emergency'), ('maternity', 'Maternity'), ('paternity', 'Paternity'), ('bereavement', 'Bereavement'), ('compensatory', 'Compensatory'), ('unpaid', 'Unpaid')], max_length=30),
        ),
        migrations.DeleteModel(
            name='LeaveType',
        ),
    ]
