# Generated by Django 6.1 on 2026-08-31 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_alter_employeeleavebalance_leave_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='leave_type',
        ),
    ]
