# Generated by Django 6.1 on 2026-08-31 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_remove_leaverequest_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('casual', 'Casual'), ('sick', 'Sick'), ('earned', 'Earned'), ('annual', 'Annual'), ('emergency', 'Emergency'), ('maternity', 'Maternity'), ('paternity', 'Paternity'), ('bereavement', 'Bereavement'), ('compensatory', 'Compensatory'), ('unpaid', 'Unpaid')], max_length=30, null=True),
        ),
    ]
