# Generated by Django 6.1 on 2026-08-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_leaverequest_leave_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleavebalance',
            name='allocated_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='employeeleavebalance',
            name='leave_type',
            field=models.CharField(choices=[('casual', 'Casual'), ('sick', 'Sick'), ('earned', 'Earned'), ('short', 'Short'), ('annual', 'Annual'), ('emergency', 'Emergency'), ('previous', 'Previous')], max_length=30),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('casual', 'Casual'), ('sick', 'Sick'), ('earned', 'Earned'), ('short', 'Short'), ('annual', 'Annual'), ('emergency', 'Emergency'), ('previous', 'Previous')], max_length=30, null=True),
        ),
    ]
