# Generated by Django 6.1 on 2026-09-01 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0023_alter_employee_manager'),
        ('leave', '0007_alter_employeeleavebalance_allocated_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='approved_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leave_requests', to='employee.employee'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='manager_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='rejected_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_leave_requests', to='employee.employee'),
        ),
    ]
