# Generated by Django 6.1 on 2026-08-18 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
