# Generated by Django 6.1 on 2026-08-20 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0009_alter_employee_email_alter_employee_phone"),
    ]

    operations = []
