# Generated by Django 6.1 on 2026-08-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_remove_employee_company_alter_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='employee/employees/'),
        ),
    ]
