# Generated by Django 6.1 on 2026-08-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_employeeaccount_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeaccount',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
