# Generated by Django 6.1 on 2026-08-25 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_alter_employeeaccount_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
