# Generated by Django 6.1 on 2026-08-26 05:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_employeeaccount_groups_employeeaccount_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeaccount',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
