# Generated by Django 6.1 on 2026-09-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0023_alter_employee_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeaccount',
            name='role',
            field=models.CharField(choices=[('employee', 'Employee'), ('manager', 'Manager'), ('hr', 'HR'), ('admin', 'Admin')], default='employee', max_length=20),
        ),
    ]
