# Generated by Django 6.1 on 2026-08-26 10:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0021_emergencycontact_employeeaddress_employeeeducation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('identity', 'Identity'), ('employee_letter', 'Employee Letter'), ('previous_experience', 'Previous Experience'), ('degree_certificate', 'Degree / Certificate'), ('other', 'Other')], max_length=50)),
                ('document_name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='employee_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employee.employee')),
            ],
        ),
    ]
