# Generated by Django 6.1 on 2026-08-18 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='Established',
            new_name='established',
        ),
    ]
