# Generated by Django 6.1 on 2026-08-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_created_at_company_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='established',
            field=models.DateField(),
        ),
    ]
